# Generated by Django 5.1.6 on 2025-03-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='course_studying',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='forms/'),
        ),
        migrations.AddField(
            model_name='form',
            name='project_details_attached',
            field=models.FileField(blank=True, null=True, upload_to='project_details/'),
        ),
        migrations.AddField(
            model_name='form',
            name='project_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='similar_project',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='student_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
