# Generated by Django 5.1.6 on 2025-03-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='pdf',
            field=models.FileField(null=True, upload_to='forms/'),
        ),
        migrations.AlterField(
            model_name='form',
            name='project_details_attached',
            field=models.FileField(null=True, upload_to='project_details/'),
        ),
    ]
