# Generated by Django 5.1.6 on 2025-03-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_form_pdf_alter_form_project_details_attached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='project_details_attached',
            field=models.BooleanField(default=False),
        ),
    ]
